const fs = require('fs');
const https = require('https');
const URLS = {
  daily: 'https://9-bit.jp/skygold/6593',
  candles: 'https://9-bit.jp/skygold/4920/',
  shards: 'https://9-bit.jp/skygold/23767/'
};
function fetchText(url){return new Promise((resolve,reject)=>{https.get(url,{headers:{'User-Agent':'Mozilla/5.0 sky-tools-bot'}},res=>{let d='';res.setEncoding('utf8');res.on('data',c=>d+=c);res.on('end',()=>resolve(d));}).on('error',reject);});}
function decode(s){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\>/gi,'\n').replace(/<\/p>|<\/div>|<\/h\d>|<\/tr>|<\/li>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/\r/g,'').split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);}
function between(lines,startRx,endRx){let a=lines.findIndex(l=>startRx.test(l)); if(a<0) a=0; let b=lines.findIndex((l,i)=>i>a && endRx.test(l)); if(b<0) b=Math.min(lines.length,a+80); return lines.slice(a,b);}
function uniq(arr){return [...new Set(arr.map(x=>x.replace(/^▲\s*/,'').trim()).filter(Boolean))];}
async function parseDaily(){const lines=decode(await fetchText(URLS.daily)); const sec=between(lines,/今日.*デイリークエスト/,/関連情報|デイリークエストとは/); const periodStart=sec.find(l=>/開始時間/.test(l))||''; const periodEnd=sec.find(l=>/終了時間/.test(l))||''; const area=(sec.find(l=>/主な対象エリア/.test(l))||'').replace('主な対象エリア','').trim()||'未取得'; let qStart=sec.findIndex(l=>/デイリークエスト.*覧|デイリークエスト一覧/.test(l)); let quests=sec.slice(qStart+1).filter(l=>!/(開始時間|終了時間|対象エリア|Image|関連情報)/.test(l)).filter(l=>l.length>3 && l.length<80).slice(0,4); return {period:[periodStart.replace('開始時間','開始 '),periodEnd.replace('終了時間','終了 ')].filter(Boolean).join(' / ')||'未取得',area,quests:uniq(quests).slice(0,4)};}
async function parseCandles(){const lines=decode(await fetchText(URLS.candles)); const sec=between(lines,/今日のデイリー大キャンドル/,/関連情報|日替わり大キャンドルとは/); const period=(sec.find(l=>/^期間/.test(l))||'').replace('期間','').trim()||'未取得'; const area=(sec.find(l=>/^エリア/.test(l))||'').replace('エリア','').trim()||'未取得'; const count=(sec.find(l=>/^個数/.test(l))||'').replace('個数','').trim()||'-'; const p=sec.filter(l=>/^▲/.test(l) || /エリア|出口|手前|左側|右側|岩|祠|船|階|入口|奥/.test(l)).filter(l=>!/^エリア|^期間|^個数|今日/.test(l)); return {period,area,count,places:uniq(p).slice(0,6)};}
async function parseShards(){const lines=decode(await fetchText(URLS.shards)); const sec=between(lines,/今日.*闇の破片|本日.*闇の破片/,/関連情報|闇の破片とは|コメント/); const date=(sec.find(l=>/月\d+日|今日|本日/.test(l))||'未取得'); const type=(sec.find(l=>/赤色|黒色|強い噴出|通常噴出|闇の破片/.test(l))||'未取得'); const area=(sec.find(l=>/エリア|場所|落ちる場所|出現場所/.test(l))||'未取得').replace(/^(エリア|場所|落ちる場所|出現場所)/,'').trim(); const times=uniq(sec.filter(l=>/\d{1,2}:\d{2}|時\d{0,2}分|偶数|奇数/.test(l))).slice(0,6); const places=uniq(sec.filter(l=>/^▲/.test(l) || /草原|雨林|峡谷|捨て|書庫|孤島|楽園|洞窟|神殿|墓所|座礁船/.test(l))).slice(0,6); return {date,type,area:area||'未取得',times:times.length?times:['未取得'],places:places.length?places:['未取得']};}
(async()=>{const data={updatedAt:new Date().toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}),source:'https://9-bit.jp/skygold/',daily:await parseDaily(),candles:await parseCandles(),shards:await parseShards()};fs.writeFileSync('data/sky.json', JSON.stringify(data,null,2));console.log(data);})().catch(e=>{console.error(e);process.exit(1);});
